java_library(
    name = "lrugctest",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/main/java/org/scode/lrugctest/cmdline:__pkg__",
        "//src/test/java/org/scode/lrugctest:__pkg__",
    ]
)
