java_binary(
    name = "lrugctest",
    srcs = ["LruGcTest.java"],
    main_class = "org.scode.lrugctest.LruGcTest",
    deps = [
        #      "//src/java/org/scode/lrugctestbazelplay/lib:greeter",
    ],
)

java_library(
    name = "lrucache",
    srcs = ["LruCache.java"],
    visibility = [
        ":__subpackages__",
    ],
)
