java_binary(
    name = "lrugctest",
    srcs = ["LruGcTest.java"],
    main_class = "org.scode.lrugctest.LruGcTest",
    deps = [
#      "//src/java/org/scode/lrugctestbazelplay/lib:greeter",
    ],
)
